In [1]:
import pandas as pd
from sklearn import preprocessing

In [2]:
data=pd.read_csv("train.csv")
data_test=pd.read_csv("test.csv")
data.head(3)

c:\users\16063\appdata\local\programs\python\python37\lib\site-packages\IPython\core\interactiveshell.py:3147: DtypeWarning: Columns (16,17,18,19,20,22,23,24,25,26,27,28,45,49,50,51) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
c:\users\16063\appdata\local\programs\python\python37\lib\site-packages\IPython\core\interactiveshell.py:3147: DtypeWarning: Columns (14,15,16,17,18,19,20,22,23,24,25,49,50,51) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,appno,application,country.alpha2,country.name,decisiondate,docname,doctypebranch,ecli,introductiondate,issue.0,...,ccl_article=6,ccl_article=7,ccl_article=8,ccl_article=9,ccl_article=p1,ccl_article=p12,ccl_article=p4,ccl_article=p6,ccl_article=p7,importance
0,2052/08,MS WORD,ru,Russian Federation,NaN,CASE OF KOKOSHKINA v. RUSSIA,CHAMBER,ECLI:CE:ECHR:2009:0528JUD000205208,NaN,NaN,...,0,0,0,0,0,0,0,0,0,4
1,4728/07,MS WORD,tr,Turkey,NaN,CASE OF ÖZCAN v. TURKEY,COMMITTEE,ECLI:CE:ECHR:2018:0710JUD000472807,NaN,NaN,...,0,0,0,0,0,0,0,0,0,4
2,44135/06,MS WORD,si,Slovenia,NaN,CASE OF DANIJEL PEČNIK v. SLOVENIA,CHAMBER,ECLI:CE:ECHR:2012:1018JUD004413506,NaN,NaN,...,1,0,0,0,0,0,0,0,0,4

In [3]:
data['application'].unique()

array(['MS WORD'], dtype=object)

In [4]:
len(data['sharepointid'].unique())

8878

In [5]:
def process(data):
    data=data.drop(['sharepointid','application','country.alpha2','decisiondate','docname','itemid','judgementdate','kpdate','languageisocode','originatingbody_type','parties.0','parties.1','parties.2','respondent.0','respondent.1','respondent.2','respondent.3',
           'respondent.4'],axis=1)
    data['ecli']=data['ecli'].iloc[:].str.slice(13,17)
    colnames=data.columns
    values=data.isna().sum()
    values
    empty=[]
    for i in range(len(colnames)):
        if(values[i]!=0):
            print(colnames[i]+"       "+str(values[i]))
            empty.append(colnames[i])

    data=data.drop(empty,axis=1)
    data.head(2)

    #data.to_csv("AS.csv")

    data['ecli']=pd.to_numeric(data['ecli'])

    le = preprocessing.LabelEncoder()

    data['doctypebranch']=le.fit_transform(data['doctypebranch'])

    data['separateopinion']=le.fit_transform(data['separateopinion'])

    data['ecli']-=1968

    data.head(3)

    e1=pd.get_dummies(data['country.name'])
    e2=pd.get_dummies(data['originatingbody_name'])
    e3=pd.get_dummies(data['originatingbody'],prefix='body_')
    e3=pd.get_dummies(data['typedescription'],prefix='type')

    df=pd.concat([e1,e2,e3],axis=1)
    df

    data=data.drop(['country.name','originatingbody_name','originatingbody','typedescription','respondentOrderEng'],axis=1)
    data=pd.concat([data,df],axis=1)

    appno=data['appno']
    appno
    return data

In [6]:
data_1=process(data)
data_1

introductiondate       8202
issue.0       6630
issue.1       7693
issue.10       8857
issue.11       8861
issue.12       8863
issue.13       8866
issue.14       8868
issue.15       8871
issue.16       8874
issue.17       8875
issue.18       8876
issue.19       8876
issue.2       8239
issue.20       8876
issue.21       8876
issue.22       8876
issue.23       8876
issue.24       8877
issue.25       8877
issue.26       8877
issue.3       8508
issue.4       8668
issue.5       8757
issue.6       8801
issue.7       8825
issue.8       8847
issue.9       8853

,appno,doctypebranch,ecli,rank,separateopinion,article=3,article=6,article=P1,article=5,article=8,...,Plenary,Second Section,Second Section Committee,Third Section,Third Section Committee,type_12,type_14,type_15,type_18,type_19
0,2052/08,0,41,685.417419,0,1,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
1,4728/07,1,50,2641.901855,0,0,0,0,1,0,...,0,0,1,0,0,0,0,1,0,0
2,44135/06,0,44,942.213440,1,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,2607/08,0,46,1121.770142,1,0,0,0,0,1,...,0,1,0,0,0,0,0,1,0,0
4,27001/06,0,41,704.821594,0,1,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8873,60085/12,1,50,2424.463379,0,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
8874,19857/09,1,48,1698.433228,0,0,0,0,1,0,...,0,0,0,0,1,0,0,1,0,0
8875,67253/01,0,39,607.506531,0,1,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
8876,26737/95,0,29,362.514832,0,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
8877,21695/05,0,39,608.091614,0,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [7]:
data_2=process(data_test)
data_2

introductiondate       4400
issue.0       3532
issue.1       4087
issue.10       4752
issue.11       4752
issue.12       4754
issue.13       4756
issue.14       4756
issue.15       4756
issue.16       4757
issue.17       4758
issue.18       4758
issue.19       4758
issue.2       4402
issue.20       4758
issue.21       4759
issue.22       4759
issue.23       4759
issue.24       4760
issue.25       4760
issue.26       4760
issue.3       4553
issue.4       4653
issue.5       4692
issue.6       4720
issue.7       4729
issue.8       4744
issue.9       4750

,appno,doctypebranch,ecli,rank,separateopinion,article=3,article=6,article=P1,article=5,article=8,...,Fourth Section Committee,Grand Chamber,Plenary,Second Section,Second Section Committee,Third Section,Third Section Committee,type_12,type_14,type_15
0,1194/04,1,43,794.766724,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,53865/11,0,47,1448.891235,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
2,43838/07,1,44,868.238831,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,11157/04,0,45,1024.145508,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
4,42443/02,0,41,672.862183,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4755,4345/06,1,48,1678.799805,0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,1
4756,10761/09,1,46,1161.929688,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4757,805/09,0,44,892.368225,0,0,0,0,0,1,...,0,0,0,0,0,1,0,0,0,1
4758,44711/16,1,50,2646.512939,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4759,21155/18,1,51,4270.748047,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [8]:
data_1=data_1.drop(['type_18','type_19'],axis=1)

In [9]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [10]:
#from sklearn.model_selection import train_test_split
#X_train, X_test, y_train, y_test = train_test_split(data, Y, test_size=0.2, random_state=123)

In [11]:
#from sklearn.metrics import accuracy_score
import xgboost as xgb

In [12]:
#model=xgb.XGBClassifier(objective ='reg:logistic', colsample_bytree = 0.3, learning_rate = 0.01,
#                max_depth = 150, alpha = 10, n_estimators = 150)
from catboost import CatBoostClassifier
model = CatBoostClassifier(loss_function='MultiClass', 
                         eval_metric='TotalF1', 
                         classes_count=5,
                         depth=16,
                         random_seed=121, 
                         iterations=100, 
                         learning_rate=0.1,
                         leaf_estimation_iterations=1,
                         l2_leaf_reg=1,
                         bootstrap_type='Bayesian', 
                         bagging_temperature=1, 
                         random_strength=1,
                         od_type='Iter', 
                         border_count=100,
                         od_wait=500)

In [13]:
#X1

In [14]:
X1=scaler.fit_transform(data_1.drop(['importance','appno'],axis=1))
from sklearn.decomposition import PCA
#pca = PCA(n_components=50)
#X1=pca.fit_transform(X1)
model.fit(X1,data_1['importance'])

Found only 4 unique classes in the data, but have defined 5 classes. Probably something is wrong with data.

0:	learn: 0.8387120	total: 31.4s	remaining: 51m 51s
1:	learn: 0.8622995	total: 1m 2s	remaining: 50m 41s
2:	learn: 0.8621011	total: 1m 9s	remaining: 37m 21s
3:	learn: 0.8518024	total: 1m 9s	remaining: 27m 46s
4:	learn: 0.8556147	total: 1m 38s	remaining: 31m 16s
5:	learn: 0.8621164	total: 1m 53s	remaining: 29m 34s
6:	learn: 0.8681442	total: 2m 17s	remaining: 30m 27s
7:	learn: 0.8719033	total: 2m 36s	remaining: 30m 5s
8:	learn: 0.8719503	total: 2m 41s	remaining: 27m 12s
9:	learn: 0.8747635	total: 3m	remaining: 27m 8s
10:	learn: 0.8787879	total: 3m 20s	remaining: 27m 3s
11:	learn: 0.8824414	total: 3m 40s	remaining: 26m 56s
12:	learn: 0.8862276	total: 3m 59s	remaining: 26m 46s
13:	learn: 0.8872601	total: 4m 19s	remaining: 26m 34s
14:	learn: 0.8898977	total: 4m 38s	remaining: 26m 19s
15:	learn: 0.8936411	total: 4m 57s	remaining: 26m 3s
16:	learn: 0.8947386	total: 5m 17s	remaining: 25m 50s
17:	learn: 0.8961749	total: 5m 38s	remaining: 25m 40s
18:	learn: 0.8966180	total: 5m 57s	remaining: 25m 25s
19:	learn: 0.8974276	total: 6m 17s	remaining: 25m 10s
20:	learn: 0.8979322	total: 6m 36s	remaining: 24m 53s
21:	learn: 0.9009012	total: 6m 55s	remaining: 24m 33s
22:	learn: 0.9031670	total: 7m 13s	remaining: 24m 11s
23:	learn: 0.9045027	total: 7m 32s	remaining: 23m 53s
24:	learn: 0.9063600	total: 7m 51s	remaining: 23m 33s
25:	learn: 0.9073163	total: 8m 9s	remaining: 23m 12s
26:	learn: 0.9102598	total: 8m 27s	remaining: 22m 51s
27:	learn: 0.9107763	total: 8m 45s	remaining: 22m 32s
28:	learn: 0.9123125	total: 9m 4s	remaining: 22m 12s
29:	learn: 0.9127811	total: 9m 22s	remaining: 21m 51s
30:	learn: 0.9142510	total: 9m 40s	remaining: 21m 31s
31:	learn: 0.9151614	total: 9m 59s	remaining: 21m 13s
32:	learn: 0.9164257	total: 10m 17s	remaining: 20m 54s
33:	learn: 0.9164301	total: 10m 35s	remaining: 20m 34s
34:	learn: 0.9165712	total: 10m 54s	remaining: 20m 14s
35:	learn: 0.9173658	total: 11m 12s	remaining: 19m 55s
36:	learn: 0.9192299	total: 11m 31s	remaining: 19m 37s
37:	learn: 0.9203125	total: 11m 52s	remaining: 19m 22s
38:	learn: 0.9216722	total: 12m 13s	remaining: 19m 7s
39:	learn: 0.9224576	total: 12m 35s	remaining: 18m 52s
40:	learn: 0.9222977	total: 12m 35s	remaining: 18m 6s
41:	learn: 0.9227674	total: 12m 55s	remaining: 17m 50s
42:	learn: 0.9242500	total: 13m 13s	remaining: 17m 32s
43:	learn: 0.9249823	total: 13m 32s	remaining: 17m 14s
44:	learn: 0.9257705	total: 13m 51s	remaining: 16m 56s
45:	learn: 0.9264771	total: 14m 10s	remaining: 16m 37s
46:	learn: 0.9265650	total: 14m 28s	remaining: 16m 19s
47:	learn: 0.9278628	total: 14m 47s	remaining: 16m 1s
48:	learn: 0.9289231	total: 15m 6s	remaining: 15m 43s
49:	learn: 0.9295377	total: 15m 25s	remaining: 15m 25s
50:	learn: 0.9300315	total: 15m 44s	remaining: 15m 7s
51:	learn: 0.9315349	total: 16m 3s	remaining: 14m 49s
52:	learn: 0.9320159	total: 16m 22s	remaining: 14m 31s
53:	learn: 0.9319006	total: 16m 41s	remaining: 14m 12s
54:	learn: 0.9332274	total: 17m	remaining: 13m 54s
55:	learn: 0.9340934	total: 17m 19s	remaining: 13m 36s
56:	learn: 0.9353977	total: 17m 38s	remaining: 13m 18s
57:	learn: 0.9357819	total: 17m 57s	remaining: 13m
58:	learn: 0.9361827	total: 18m 17s	remaining: 12m 42s
59:	learn: 0.9362954	total: 18m 37s	remaining: 12m 24s
60:	learn: 0.9371275	total: 18m 55s	remaining: 12m 6s
61:	learn: 0.9376109	total: 19m 14s	remaining: 11m 47s
62:	learn: 0.9384506	total: 19m 32s	remaining: 11m 28s
63:	learn: 0.9388123	total: 19m 51s	remaining: 11m 10s
64:	learn: 0.9391658	total: 20m 10s	remaining: 10m 51s
65:	learn: 0.9396494	total: 20m 29s	remaining: 10m 33s
66:	learn: 0.9400330	total: 20m 47s	remaining: 10m 14s
67:	learn: 0.9397777	total: 21m 6s	remaining: 9m 56s
68:	learn: 0.9401381	total: 21m 25s	remaining: 9m 37s
69:	learn: 0.9404053	total: 21m 44s	remaining: 9m 19s
70:	learn: 0.9413251	total: 22m 3s	remaining: 9m
71:	learn: 0.9423908	total: 22m 21s	remaining: 8m 41s
72:	learn: 0.9421458	total: 22m 40s	remaining: 8m 23s
73:	learn: 0.9423012	total: 22m 59s	remaining: 8m 4s
74:	learn: 0.9437306	total: 23m 18s	remaining: 7m 46s
75:	learn: 0.9441861	total: 23m 36s	remaining: 7m 27s
76:	learn: 0.9447691	total: 23m 55s	remaining: 7m 8s
77:	learn: 0.9453669	total: 24m 14s	remaining: 6m 50s
78:	learn: 0.9460722	total: 24m 32s	remaining: 6m 31s
79:	learn: 0.9460722	total: 24m 51s	remaining: 6m 12s
80:	learn: 0.9469155	total: 25m 9s	remaining: 5m 54s
81:	learn: 0.9473817	total: 25m 28s	remaining: 5m 35s
82:	learn: 0.9477512	total: 25m 46s	remaining: 5m 16s
83:	learn: 0.9478592	total: 26m 5s	remaining: 4m 58s
84:	learn: 0.9477335	total: 26m 24s	remaining: 4m 39s
85:	learn: 0.9482185	total: 26m 43s	remaining: 4m 20s
86:	learn: 0.9490404	total: 27m 1s	remaining: 4m 2s
87:	learn: 0.9498810	total: 27m 20s	remaining: 3m 43s
88:	learn: 0.9502408	total: 27m 38s	remaining: 3m 25s
89:	learn: 0.9511830	total: 27m 57s	remaining: 3m 6s
90:	learn: 0.9513008	total: 28m 16s	remaining: 2m 47s
91:	learn: 0.9511237	total: 28m 35s	remaining: 2m 29s
92:	learn: 0.9511080	total: 28m 54s	remaining: 2m 10s
93:	learn: 0.9516893	total: 29m 13s	remaining: 1m 51s
94:	learn: 0.9529759	total: 29m 32s	remaining: 1m 33s
95:	learn: 0.9530948	total: 29m 51s	remaining: 1m 14s
96:	learn: 0.9535581	total: 30m 10s	remaining: 56s
97:	learn: 0.9541359	total: 30m 28s	remaining: 37.3s
98:	learn: 0.9542591	total: 30m 48s	remaining: 18.7s
99:	learn: 0.9548852	total: 31m 6s	remaining: 0us

In [15]:
X2=scaler.transform(data_2.drop(['appno'],axis=1))
#X2=pca.fit_transform(X2)
res=model.predict(X2)

In [16]:
res

array([[4],
       [4],
       [4],
       ...,
       [4],
       [4],
       [4]], dtype=int64)

In [17]:
OP=pd.DataFrame()
OP['appno']=data_2['appno']
OP['importance']=res

In [18]:
#OP.to_csv("my_res1.csv",index=False)
OP['importance']

0       4
1       4
2       4
3       3
4       3
       ..
4755    4
4756    4
4757    4
4758    4
4759    4
Name: importance, Length: 4760, dtype: int64

In [19]:
OP.to_csv("MY_RES_IMPEACH1.csv",index=False)